name: Lint

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: stefanoeb/eslint-action@1.0.2
      with:
        files: src/